### ISSUE TITLE
Issue with import requests 

### ISSUE THREAD

**Issue by zhay47** [Mr-Zanzibar/Discord-Nitro-Gen#1] opened 2024-06-10 09:12 UTC
When
![image_2024-06-10_051148811](https://github.com/Mr-Zanzibar/Discord-Nitro-Gen/assets/55160279/9f92569e-5911-47d5-a55f-5c6527c211ff)
 starting the bat file this happens right away.

**Comment by Mr-Zanzibar** [comment] 2024-07-26 21:12
the issue is now fixed.

**Closed** 2024-07-26 21:12 UTC
